package pd1_rulevics_25;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projekta darbs Nr.1. Testēšanas sistēmas izveidošana
//  @ File Name : Question.java
//  @ Date : 29.04.2024
//  @ Author : Nikita Rulevics
//
//




public class Question {
	private String text;
	private String answer;
	private int correctAnswer;
        
	public void Question(String text, String answers, int correctAnswer) {
            
	}
	
	public String getText() {
            return text;
	}
	
	public String getAnswers() {
            return answer;
	}
	
	public boolean isCorrect(int answer) {
	    return true;
            
	}
}
