package pd1_rulevics_25;

//
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projekta darbs Nr.1. Testēšanas sistēmas izveidošana
//  @ File Name : Student.java
//  @ Date : 29.04.2024
//  @ Author : Nikita Rulevics
//
//
public class Student extends User {

    public Student(String name, String surname, String username, String password, String userType) {
        super(name, surname, username, password, userType);
    }

    public Student(String name, String username, String password, String userType) {
        super(name, username, password, userType);
    }

    public void displayMarks(JTable jTable1) {
        DataBase db = new DataBase();
        ResultSet rs = null;
        PreparedStatement pst = null;

        try {
            Connection con = db.connect();

            String sql = "SELECT TestName, Mark FROM marks WHERE UserName=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, this.username); // используем this.username, так как он принадлежит текущему студенту
            rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                String testName = rs.getString("TestName");
                String mark = rs.getString("Mark");
                model.addRow(new Object[]{testName, mark});
            }

            jTable1.setModel(model);
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void displayTest(String testName, JLabel TestNameLabel, JLabel[] questionLabels, JRadioButton[][] answerButtons, JDialog mainFrameStudent, JDialog mainFrameTeacher, JDialog testFrame) {
        DataBase db = new DataBase();
        ResultSet rs = null;
        PreparedStatement pst = null;

        if (testName == null) {
            Logu_Redaktors loguRedaktors = new Logu_Redaktors();
            loguRedaktors.showError("Tests nav izvelēts!");
            return;
        }

        try {
            Connection con = db.connect();
            TestNameLabel.setText(testName);

            String sql = "SELECT QuestionText, AnswerFirst, AnswerSecond, AnswerThird FROM test WHERE TestName=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, testName);
            rs = pst.executeQuery();

            int questionIndex = 0;

            while (rs.next() && questionIndex < 5) {
                String questionText = rs.getString("QuestionText");
                String answerFirst = rs.getString("AnswerFirst");
                String answerSecond = rs.getString("AnswerSecond");
                String answerThird = rs.getString("AnswerThird");

                questionLabels[questionIndex].setText(questionText);
                answerButtons[questionIndex][0].setText(answerFirst);
                answerButtons[questionIndex][1].setText(answerSecond);
                answerButtons[questionIndex][2].setText(answerThird);

                questionIndex++;
            }

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        mainFrameStudent.dispose();
        mainFrameTeacher.dispose();
        testFrame.setVisible(true);
        testFrame.pack();
        testFrame.setLocationRelativeTo(null);
    }
}
