package pd1_rulevics_25;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projekta darbs Nr.1. Testēšanas sistēmas izveidošana
//  @ File Name : Student.java
//  @ Date : 29.04.2024
//  @ Author : Nikita Rulevics
//
//

public class Student extends User {
    private int questionCount;
    private int rightAnswers;

    public Student(String name, String surname, String login, String password, String userType) {
        super(name, surname, login, password, userType);
        this.questionCount = 0;
        this.rightAnswers = 0;
    }
    
    public int getCorrectAnswer(Question question) {
        // Logic to get the correct answer
        return 0;
    }
    
    public void giveAnswer(Question question, int answer) {
        // Logic to give an answer
    }
    
    public void clear() {
        // Clear student data
    }
}
