package pd1_rulevics_25;

import com.sun.tools.javac.util.StringUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projekta darbs Nr.1. Testēšanas sistēmas izveidošana
//  @ File Name : Teacher.java
//  @ Date : 29.04.2024
//  @ Author : Nikita Rulevics
//
//




public class Teacher extends User {
    
    public Teacher(String name, String surname, String username, String password, String userType) {
        super(name, surname, username, password, userType);
    }
    
    public Teacher(String name, String username, String password, String userType){
        super(name, username, password, userType);
    }
    
    public void populateMarksTable(JTable jTable4) {
        DataBase db = new DataBase();
        ResultSet rs = null, rs2 = null;
        PreparedStatement pst = null, pst2 = null;

        try {
            Connection con = db.connect();

            String sql = "SELECT UserName, TestName, Mark FROM marks";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                String userName = rs.getString("UserName");
                String testName = rs.getString("TestName");
                String mark = rs.getString("Mark");

                sql = "SELECT FirstName, LastName FROM users WHERE UserName=? ";
                pst2 = con.prepareStatement(sql);
                pst2.setString(1, userName);
                rs2 = pst2.executeQuery(); 
                while (rs2.next()) {
                    String firstName = rs2.getString("FirstName");
                    String lastName = rs2.getString("LastName");
                    model.addRow(new Object[]{firstName, lastName, testName, mark});
                }

                rs2.close(); 
                pst2.close(); 
            }

            jTable4.setModel(model);
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void saveNewMarks(JTable jTable4){
        DataBase db = new DataBase();
        Connection con = null;
        PreparedStatement pst = null;
        boolean hasInvalidMarks = false;
        Logu_Redaktors loguRedaktors = new Logu_Redaktors();
        
        try {
            con = db.connect();

            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            int rowCount = model.getRowCount();

            String sql = "UPDATE marks SET Mark=? WHERE UserName=? AND TestName=?";
            pst = con.prepareStatement(sql);

            for (int i = 0; i < rowCount; i++) {
                String mark = (String) model.getValueAt(i, 3);
                try {
                    int markValue = Integer.parseInt(mark);
                    if (markValue < 1 || markValue > 10) {
                        hasInvalidMarks = true;
                        String firstName = (String) model.getValueAt(i, 0);
                        String lastName = (String) model.getValueAt(i, 1);
                        loguRedaktors.showError("Nepareizs vērtējums par lietotāju - \"" + firstName + " " + lastName + "\".");
                    }
                } catch (NumberFormatException e) {
                    hasInvalidMarks = true;
                    String firstName = (String) model.getValueAt(i, 0);
                    String lastName = (String) model.getValueAt(i, 1);
                    loguRedaktors.showError("Nepareizs vērtējums par lietotāju - \"" + firstName + " " + lastName + "\".");
                }
            }
            
            if (!hasInvalidMarks) {
                for (int i = 0; i < rowCount; i++) {
                    String firstName = (String) model.getValueAt(i, 0);
                    String lastName = (String) model.getValueAt(i, 1);
                    String testName = (String) model.getValueAt(i, 2);
                    String mark = (String) model.getValueAt(i, 3);

                    String userName = loguRedaktors.getUserName(con, firstName, lastName);

                    pst.setString(1, mark);
                    pst.setString(2, userName);
                    pst.setString(3, testName);

                    pst.executeUpdate();

                }
                loguRedaktors.showInfo("Jūs esat veiksmīgi nomainījuši atzīmes!");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        populateMarksTable(jTable4);
    }
    
    public void deleteMark(JTable jTable4) {
        Logu_Redaktors loguRedaktors = new Logu_Redaktors();
        int selectedRow = jTable4.getSelectedRow();
        
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            String firstName = (String) model.getValueAt(selectedRow, 0);
            String lastName = (String) model.getValueAt(selectedRow, 1);
            String testName = (String) model.getValueAt(selectedRow, 2);

            DataBase db = new DataBase();
            Connection con = null;
            PreparedStatement pst = null;

            try {
                con = db.connect();
                String userName = loguRedaktors.getUserName(con, firstName, lastName);

                String sql = "DELETE FROM marks WHERE UserName=? AND TestName=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, userName);
                pst.setString(2, testName);
                pst.executeUpdate();

                model.removeRow(selectedRow);
                loguRedaktors.showInfo("Vērtējums ir veiksmīgi izdzēsts!");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } 
        } else {
            loguRedaktors.showError("Nav izvēlēta neviena rinda!");
        }
    }
    
    public void deleteTest(JList<String> jList2, JTextArea TestDescriptionTextArea1) {
        String selectedTest = jList2.getSelectedValue();
        Logu_Redaktors loguRedaktors = new Logu_Redaktors(); 
        
        if (selectedTest != null) {
            DataBase db = new DataBase();
            Connection con = null;
            PreparedStatement pst = null;
            try {
                con = db.connect();
                String sql = "DELETE FROM test WHERE TestName = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1, selectedTest);
                pst.executeUpdate();
                con.close();
                DefaultListModel<String> model = (DefaultListModel<String>) jList2.getModel();
                model.removeElement(selectedTest);
                loguRedaktors.showInfo("Tests ir veiksmīgi izdzēsts!");
                TestDescriptionTextArea1.setText("");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }else{
            loguRedaktors.showError("Tests nav izvelēts!");
        }
    }
    
}