package pd1_rulevics_25;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projekta darbs Nr.1. Testēšanas sistēmas izveidošana
//  @ File Name : Teacher.java
//  @ Date : 29.04.2024
//  @ Author : Nikita Rulevics
//
//




public class Teacher extends User {
    
    public Teacher(String name, String surname, String login, String password, String userType) {
        super(name, surname, login, password, userType);
    }
    
    public void deleteUser(String login) {
        // Logic to delete user
    }
    
    public void addUser(String name, String surname, String login, String password, String userType) {
        // Logic to add a new user
    }
    
    public void editUser(String login, User user) {
        // Logic to edit user information
    }
}