package pd1_rulevics_25;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projekta darbs Nr.1. Testēšanas sistēmas izveidošana
//  @ File Name : User.java
//  @ Date : 29.04.2024
//  @ Author : Nikita Rulevics
//
//




public class User {
    private String name;
    private String surname;
    private String login;
    private String password;
    private String userType;

    public User(String name, String surname, String login, String password, String userType) {
        this.name = name;
        this.surname = surname;
        this.login = login;
        this.password = password;
        this.userType = userType;
    }

    public String getName() {
        return name;
    }

    public String getSurname() {
        return surname;
    }

    public String getLogin() {
        return login;
    }

    public String getPassword() {
        return password;
    }

    public String getUserType() {
        return userType;
    }
    
    public boolean enter(String login, String password) {
        return this.login.equals(login) && this.password.equals(password);
    }
}
